
package org.mule.example.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Tue Feb 24 13:50:39 JST 2009
 * Generated source version: 2.1.2
 * 
 */

public final class Echo_EchoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://echo.example.mule.org/", "EchoService");

    private Echo_EchoPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EchoService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EchoService ss = new EchoService(wsdlURL, SERVICE_NAME);
        Echo port = ss.getEchoPort();  
        
        {
        System.out.println("Invoking echo...");
        java.lang.String _echo_text = "";
        java.lang.String _echo__return = port.echo(_echo_text);
        System.out.println("echo.result=" + _echo__return);


        }

        System.exit(0);
    }

}
