package org.mule.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Tue Feb 24 13:50:39 JST 2009
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://echo.example.mule.org/", name = "Echo")
@XmlSeeAlso({ObjectFactory.class})
public interface Echo {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://echo.example.mule.org/", className = "org.mule.example.client.Echo_Type")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://echo.example.mule.org/", className = "org.mule.example.client.EchoResponse")
    @WebMethod
    public java.lang.String echo(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );
}
