
package org.mule.example.echo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.6
 * Mon Sep 01 12:13:23 JST 2008
 * Generated source version: 2.0.6
 * 
 */

public final class Echo_EchoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://echo.example.mule.org/", "EchoService");

    private Echo_EchoPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EchoService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EchoService ss = new EchoService(wsdlURL, SERVICE_NAME);
        Echo port = ss.getEchoPort();  
        
        {
        System.out.println("Invoking echo...");
        java.lang.String _echo_textVal = "";
        javax.xml.ws.Holder<java.lang.String> _echo_text = new javax.xml.ws.Holder<java.lang.String>(_echo_textVal);
        port.echo(_echo_text);

        System.out.println("echo._echo_text=" + _echo_text.value);

        }

        System.exit(0);
    }

}
