
package org.mule.example.echo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import org.mule.example.echo.Echo;

/**
 * This class was generated by Apache CXF 2.0.6
 * Mon Sep 01 12:13:23 JST 2008
 * Generated source version: 2.0.6
 * 
 */

@WebServiceClient(name = "EchoService", targetNamespace = "http://echo.example.mule.org/", wsdlLocation = "file:/C:/s2Mule/mule_forge_trunk/trunk/src/test/functional/resources/org/mule/extras/seasar2/receiver/cxf/EchoUMO.xml")
public class EchoService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://echo.example.mule.org/", "EchoService");
    public final static QName EchoPort = new QName("http://echo.example.mule.org/", "EchoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/s2Mule/mule_forge_trunk/trunk/src/test/functional/resources/org/mule/extras/seasar2/receiver/cxf/EchoUMO.xml");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/s2Mule/mule_forge_trunk/trunk/src/test/functional/resources/org/mule/extras/seasar2/receiver/cxf/EchoUMO.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EchoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EchoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns EchoPort
     */
    @WebEndpoint(name = "EchoPort")
    public Echo getEchoPort() {
        return super.getPort(EchoPort, Echo.class);
    }

}
