
package org.mule.example.echo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.6
 * Mon Sep 01 12:13:23 JST 2008
 * Generated source version: 2.0.6
 * 
 */

@WebService(targetNamespace = "http://echo.example.mule.org/", name = "Echo")

public interface Echo {

    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://echo.example.mule.org/", className = "org.mule.example.echo.EchoResponse")
    @RequestWrapper(localName = "echo", targetNamespace = "http://echo.example.mule.org/", className = "org.mule.example.echo.Echo_Type")
    @WebMethod
    public void echo(
        @WebParam(mode = WebParam.Mode.INOUT, name = "text", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> text
    );
}
