
package org.mule.extras.seasar2.ws.hello;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Fri Mar 27 19:18:59 JST 2009
 * Generated source version: 2.1.2
 * 
 */

public final class HelloWorld_HelloWorldPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf.receiver.seasar2.extras.mule.org/", "HelloWorld");

    private HelloWorld_HelloWorldPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HelloWorld_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorld_Service ss = new HelloWorld_Service(wsdlURL, SERVICE_NAME);
        HelloWorld port = ss.getHelloWorldPort();  
        
        {
        System.out.println("Invoking hello...");
        java.lang.String _hello_src = "";
        java.lang.String _hello__return = port.hello(_hello_src);
        System.out.println("hello.result=" + _hello__return);


        }

        System.exit(0);
    }

}
